# USING NUMPY


In [2]:
lst = [1,2,3]
import numpy as np

arr= np.array(lst)
arr

array([1, 2, 3])

In [5]:
#syntax: start,stop, step
arr=np.arange(0,11,2)
arr

array([ 0,  2,  4,  6,  8, 10])

In [6]:
lst = [(1,2,3),(4,5,6),(7,8,9)]
arr= np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.zeros(4)

array([0., 0., 0., 0.])

In [9]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
#linspace: gives an array of random numbers bw the specified start and stop nos.(start, stop, nos required)

np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [14]:
#identity matrix: consists of zeros and 1s in diagnol- equal no. of rows and columns
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
#uniformly distributed random numbers from zero to one
np.random.rand(5)

array([0.55888663, 0.2769151 , 0.86736891, 0.95921447, 0.37638323])

In [17]:
#note: tuple is not passed here unlike other functions- 2D
np.random.rand(3,4)

array([[0.65885388, 0.88342286, 0.75746522, 0.51012605],
       [0.75248667, 0.49746703, 0.50528239, 0.29966291],
       [0.53692397, 0.93649179, 0.75508255, 0.53406186]])

In [18]:
#randn- return samples as gaussian or normal distribution
np.random.randn(3)

array([-1.06272733, -1.09286192, -0.68565251])

In [19]:
np.random.randn(5,5)

array([[-1.67130048,  1.20591591,  0.73651615,  0.50292908,  0.80471015],
       [ 0.12729148,  0.05375382,  0.9852833 ,  0.03215733, -0.48452288],
       [-0.07636618,  0.89019329, -0.7965213 , -0.274437  , -1.80816543],
       [-0.75412065, -0.79276062,  1.73615695, -0.25084523,  0.16168195],
       [-1.03954484,  1.01633052,  1.12052896, -1.11929925,  0.16216073]])

In [24]:
#randint- printing 10 random integers in a range. syntax(low, high, nos reqd) where chances of selection of low is 1/2, but high is exclusive
ar=np.random.randint(0,100,10)

In [22]:
arr=np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
#total size of the new array must be unchanged
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
ar.max()

78

In [26]:
ar.min()

10

In [27]:
#location of the max value
ar.argmax()

4

In [28]:
#location of min value
ar.argmin()

6

In [30]:
#notice that brackets arent used here
ar.shape

(10,)

# NUMPY INDEXING AND SELECTION

In [32]:
arr = np.arange(0,11)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
arr[7]

7

In [36]:
#printing the array till end, when initial index is given, initial index is inclusive and final index isnt
print(arr[0:])
print(arr[4:])

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 4  5  6  7  8  9 10]


In [37]:
arr[1:5]

array([1, 2, 3, 4])

In [38]:
#syntax: (start, stop, skip/step size)
arr[1:11:2]

array([1, 3, 5, 7, 9])

In [39]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [40]:
slice = arr[0:6]
slice

array([100, 100, 100, 100, 100,   5])

In [42]:
#changing every element to 10
slice[:]=10
slice

array([10, 10, 10, 10, 10, 10])

In [43]:
#changes are reflected back in the original array
arr

array([10, 10, 10, 10, 10, 10,  6,  7,  8,  9, 10])

In [44]:
#to specifically make a copy of an array
arr_copy = arr.copy()

In [45]:
arr_copy[:]=100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [46]:
#changes are not reflected back
arr

array([10, 10, 10, 10, 10, 10,  6,  7,  8,  9, 10])

In [48]:
#2D array
arr_2d = np.array(([2,10,11],[3,4,5],[7,9,8] ))
arr_2d

array([[ 2, 10, 11],
       [ 3,  4,  5],
       [ 7,  9,  8]])

In [49]:
#indexing
arr_2d[0][2]

11

In [51]:
#single bracket notation
arr_2d[0,2]

11

In [54]:
#displayed row 0,1 excluding index 2 and started from column 1 till end
arr_2d[:2,1:]

array([[10, 11],
       [ 4,  5]])

In [55]:
#breaking down further
arr_2d[:2]

array([[ 2, 10, 11],
       [ 3,  4,  5]])

In [58]:
arr_2d[:,1:]

array([[10, 11],
       [ 4,  5],
       [ 9,  8]])

In [59]:
#conditional selection
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
bool_arr=arr>5
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [63]:
#returnswhere the comparison is true
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [64]:
#or
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [67]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [68]:
arr_2d[1:3,4:7]

array([[14, 15, 16],
       [24, 25, 26]])

In [69]:
#numpy operations
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
#add, subtract, multiply 2 arrays

arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [71]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [72]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [73]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [74]:
arr*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [75]:
arr/arr

C:\Users\Veer\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [76]:
1/arr

C:\Users\Veer\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [77]:
arr**4

array([    0,     1,    16,    81,   256,   625,  1296,  2401,  4096,
        6561, 10000], dtype=int32)

In [78]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [79]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [80]:
np.max(arr)

10

In [81]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [82]:
np.log(arr)

C:\Users\Veer\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])